-- Esquema inicial: tabla de planes de obra social.
CREATE TABLE health_plan (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinics       VARCHAR(255),
    comments      VARCHAR(255),
    document_path VARCHAR(255)
);
