-- Usuarios internos (agentes/vendedores) y sus roles.
CREATE TABLE user_account (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    enabled  BOOLEAN      NOT NULL,
    CONSTRAINT uk_user_account_username UNIQUE (username)
);

CREATE TABLE user_account_role (
    user_account_id BIGINT      NOT NULL,
    role            VARCHAR(50) NOT NULL,
    CONSTRAINT fk_user_account_role_user FOREIGN KEY (user_account_id) REFERENCES user_account (id)
);
