-- Enriquecimiento del plan como producto vendible.
ALTER TABLE health_plan
    ADD COLUMN name           VARCHAR(255),
    ADD COLUMN coverage_level VARCHAR(50),
    ADD COLUMN active         BOOLEAN NOT NULL DEFAULT TRUE;

-- Catálogo de franjas etarias (compartido por todos los planes).
CREATE TABLE age_band (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(100) NOT NULL,
    age_from INTEGER      NOT NULL,
    age_to   INTEGER      NOT NULL
);

-- Tabla de precios: monto por (plan, franja) con vigencia.
CREATE TABLE plan_price (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id     BIGINT        NOT NULL,
    age_band_id BIGINT        NOT NULL,
    amount      NUMERIC(12,2) NOT NULL,
    valid_from  DATE          NOT NULL,
    valid_to    DATE,
    CONSTRAINT fk_plan_price_plan     FOREIGN KEY (plan_id)     REFERENCES health_plan (id),
    CONSTRAINT fk_plan_price_age_band FOREIGN KEY (age_band_id) REFERENCES age_band (id)
);

-- Franjas etarias estándar.
INSERT INTO age_band (name, age_from, age_to) VALUES
    ('0-18',  0,  18),
    ('19-25', 19, 25),
    ('26-35', 26, 35),
    ('36-45', 36, 45),
    ('46-55', 46, 55),
    ('56-65', 56, 65),
    ('66+',   66, 120);
